name: mygenericbinder9
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - python=3.7
  - scipy
  - pytorch==1.4.0
  - cudatoolkit==10.1.243
  - pip
  - pip:
    - pathtools==0.1.2
    - streamlit
    - jupyter-server-proxy
    - nbserverproxy  
    - nbgitpuller
    - torchvision==0.5.0
    - opencv-python==4.2.0.32
    - vispy==0.6.4
    - moviepy==1.0.2
    - transforms3d==0.3.1
    - networkx==2.3
